<?php

namespace database\seeders;

use App\Domain\Models\Customer;
use App\Domain\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CustomerTableSeeder extends Seeder
{
    public $customers =  [
        [
            'id' => 1,
            'reseller_id' => 0,
            'name' => 'sparkfore',
            'slugified_name' => 'sparkfore',
            'organization_no' => '559294-4820',
            'user_email' => 'anders.stenmark@autotech.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura@autotech.se',
            'invoice_reference' => 'Sparkfore',
            'invoice_annotation' => 'Test annotation'
        ],
        [
            'id' => 2,
            'reseller_id' => 1,
            'name' => 'DGM Sverige AB',
            'slugified_name' => 'dgm-sverige-ab',
            'organization_no' => '556598-2526',
            'user_email' => 'joakim@dgm.se',
            'invoice_type' => 'email',
            'invoice_address' => 'invoice@dgm.se',
            'invoice_reference' => 'Joakim Nielsen',
            'invoice_annotation' => ''
        ],
        [
            'id' => 3,
            'reseller_id' => 1,
            'name' => 'ULLA',
            'slugified_name' => 'ulla',
            'organization_no' => 'https://ullapharmsci.org/',
            'user_email' => 'onlinecourses@ullapharmsci.org',
            'invoice_type' => 'email',
            'invoice_address' => 'onlinecourses@ullapharmsci.org',
            'invoice_reference' => 'Sonja van Scheijen',
            'invoice_annotation' => 'ULLA online courses'
        ],
        [
            'id' => 4,
            'reseller_id' => 1,
            'name' => 'Försvarsmakten',
            'slugified_name' => 'forsvarsmakten',
            'organization_no' => '202100-4615',
            'user_email' => 'jonas.almert@mil.se',
            'invoice_type' => 'email',
            'invoice_address' => 'efakt.5594024472@cogidocs.net',
            'invoice_reference' => 'Nathalie Sahlström',
            'invoice_annotation' => '23.3-8027-21 FM2023-5454'
        ],
        [
            'id' => 5,
            'reseller_id' => 1,
            'name' => 'AB Åkerikonsult',
            'slugified_name' => 'ab-akerikonsult',
            'organization_no' => '556098-6696',
            'user_email' => 'Marcus.Johansson@akeri.se',
            'invoice_type' => 'email',
            'invoice_address' => 'efaktura@akeri.se',
            'invoice_reference' => 'Marcus Johansson',
            'invoice_annotation' => 'Marcus Johansson EPV-WEB'
        ],
        [
            'id' => 6,
            'reseller_id' => 1,
            'name' => 'Neoventa Medical AB',
            'slugified_name' => 'neoventa-medical-ab',
            'organization_no' => '556773-4784',
            'user_email' => 'ida.larsson@neoventa.com',
            'invoice_type' => 'email',
            'invoice_address' => 'finance@neoventa.com',
            'invoice_reference' => 'Ida Larsson',
            'invoice_annotation' => ''
        ],
        [
            'id' => 7,
            'reseller_id' => 1,
            'name' => 'Poz Academy AB',
            'slugified_name' => 'poz-academy-ab',
            'organization_no' => '556773-4784',
            'user_email' => 'robin@poz.se',
            'invoice_type' => 'email',
            'invoice_address' => 'magnus@pozacademy',
            'invoice_reference' => 'Robin Håkansson',
            'invoice_annotation' => ''
        ],
        [
            'id' => 8,
            'reseller_id' => 1,
            'name' => 'Höganäs AB',
            'slugified_name' => 'hoganas-ab',
            'organization_no' => '556005-0121',
            'user_email' => 'Therese.Jonmark@hoganas.com',
            'invoice_type' => 'email',
            'invoice_address' => 'reskontraHAB@hoganas.com',
            'invoice_reference' => 'Therese Jönmark',
            'invoice_annotation' => ''
        ],
        [
            'id' => 9,
            'reseller_id' => 1,
            'name' => 'KWT Utbildning AB',
            'slugified_name' => 'kwt-utbildning-ab',
            'organization_no' => '556676-8478',
            'user_email' => 'kai@kwt.nu',
            'invoice_type' => 'email',
            'invoice_address' => 'kai@kwt.nu',
            'invoice_reference' => 'Kai Wänghult',
            'invoice_annotation' => ''
        ],
        [
            'id' => 10,
            'reseller_id' => 1,
            'name' => 'Road Safety Sweden AB',
            'slugified_name' => 'road-safety-sweden-ab',
            'organization_no' => '559323-4395',
            'user_email' => 'info@freddesutbildning.se',
            'invoice_type' => 'email',
            'invoice_address' => 'info@freddesutbildning.se',
            'invoice_reference' => 'Fredrik Strahl Bursell',
            'invoice_annotation' => ''
        ],
        [
            'id' => 11,
            'reseller_id' => 1,
            'name' => 'JOST-Werke Deutschland GmbH',
            'slugified_name' => 'jost-werke-deutschland-gmbh',
            'organization_no' => 'https://www.jost-world.com/de/',
            'user_email' => 'florian.baumann@jost-world.com',
            'invoice_type' => 'email',
            'invoice_address' => '1000.invoice@jost-world.com',
            'invoice_reference' => 'Florian Baumann',
            'invoice_annotation' => '4500303124'
        ],
        [
            'id' => 12,
            'reseller_id' => 1,
            'name' => 'Lantmännen ek för Agro Oil',
            'slugified_name' => 'lantmannen-ek-for-agro-oil',
            'organization_no' => '769605-2856',
            'user_email' => 'Sebastian Norman',
            'invoice_type' => 'email',
            'invoice_address' => 'lantmannen-ekfor@pdf.scancloud.se',
            'invoice_reference' => 'Sebastian Norman',
            'invoice_annotation' => ''
        ],
        [
            'id' => 13,
            'reseller_id' => 1,
            'name' => 'Electrolux Professional AB (publ)',
            'slugified_name' => 'electrolux-professional-ab-publ',
            'organization_no' => '556003-0354',
            'user_email' => 'magnus.martensson@electroluxprofessional.com',
            'invoice_type' => 'email',
            'invoice_address' => 'finance.ljungby@electroluxprofessional.com',
            'invoice_reference' => 'Andreas Dessecker',
            'invoice_annotation' => ''
        ],
        [
            'id' => 14,
            'reseller_id' => 1,
            'name' => 'Recipharm Karlskoga AB',
            'slugified_name' => 'recipharm-karlskoga-ab',
            'organization_no' => '556662-4366',
            'user_email' => 'elisabet.myhrman@recipharm.com',
            'invoice_type' => 'email',
            'invoice_address' => 'REC0000@tps.banctec.se',
            'invoice_reference' => 'Elisabet Myhrman',
            'invoice_annotation' => ''
        ],
        [
            'id' => 15,
            'reseller_id' => 1,
            'name' => 'R1 Trafikskolan H. Månsson AB',
            'slugified_name' => 'r1-trafikskolan-h-mansson-ab',
            'organization_no' => '556623-8266',
            'user_email' => 'hakan@r1.se',
            'invoice_type' => 'email',
            'invoice_address' => 'hakan@r1.se',
            'invoice_reference' => 'Håkan Månsson',
            'invoice_annotation' => ''
        ],
        [
            'id' => 16,
            'reseller_id' => 1,
            'name' => 'Bothniagruppen AB',
            'slugified_name' => 'bothniagruppen-ab',
            'organization_no' => '556790-4361',
            'user_email' => 'linus@bothniagruppen.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura@bothniagruppen.se',
            'invoice_reference' => 'Linus Josefsson',
            'invoice_annotation' => ''
        ],
        [
            'id' => 17,
            'reseller_id' => 1,
            'name' => 'Olofsfors Aktiebolag',
            'slugified_name' => 'olofsfors-aktiebolag',
            'organization_no' => '556203-8298',
            'user_email' => 'erik.sollen@olofsfors.se',
            'invoice_type' => 'mail',
            'invoice_address' => 'Olofsfors Aktiebolag, Olofsfors 11 914 91 Nordmaling',
            'invoice_reference' => 'Erik Sollén',
            'invoice_annotation' => ''
        ],
        [
            'id' => 18,
            'reseller_id' => 1,
            'name' => 'Brokk Aktiebolag',
            'slugified_name' => 'brokk-aktiebolag',
            'organization_no' => '556115-6224',
            'user_email' => 'martin.burstrom@brokk.com',
            'invoice_type' => 'email',
            'invoice_address' => 'email',
            'invoice_reference' => 'Martin Burström',
            'invoice_annotation' => ''
        ],
        [
            'id' => 19,
            'reseller_id' => 1,
            'name' => 'Meetme Psykologkonsult AB',
            'slugified_name' => 'meetme-psykologkonsult-ab',
            'organization_no' => '556529-4112',
            'user_email' => 'hans.wickstrom@kbtanalys.se',
            'invoice_type' => 'mail',
            'invoice_address' => 'MeetMe Psykologkonsult AB, Åvägen 19, 443 31 LERUM',
            'invoice_reference' => 'Hans Wickström',
            'invoice_annotation' => ''
        ],
        [
            'id' => 20,
            'reseller_id' => 1,
            'name' => 'DGM Netherlands',
            'slugified_name' => 'dgm-netherlands',
            'organization_no' => 'https://www.dgm.nl/',
            'user_email' => 'cesca@dgm.nl',
            'invoice_type' => 'mail',
            'invoice_address' => 'DGM NETHERLANDS B.V., Zandsteen 46, 2132 MR Hoofddorp',
            'invoice_reference' => 'Cesca Nielsen-Pétillon',
            'invoice_annotation' => ''
        ],
        [
            'id' => 21,
            'reseller_id' => 1,
            'name' => 'Utbildarna i Helsingborg AB',
            'slugified_name' => 'utbildarna-i-helsingborg-ab',
            'organization_no' => '556605-6429',
            'user_email' => 'andreas.sjostrom@utbildarna.com',
            'invoice_type' => 'mail',
            'invoice_address' => 'Utbildarna AB, Atlantgatan 6, 252 25 Helsingborg',
            'invoice_reference' => 'Andreas Sjöström',
            'invoice_annotation' => ''
        ],
        [
            'id' => 22,
            'reseller_id' => 1,
            'name' => 'skellefteakommun',
            'slugified_name' => 'skellefteakommun',
            'organization_no' => '212000-2643',
            'user_email' => 'sara.hallgren@skelleftea.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'Skellefteå kommun, Box 804, 931 28 Skellefteå',
            'invoice_reference' => 'Sara Hällgren',
            'invoice_annotation' => ''
        ],
        [
            'id' => 23,
            'reseller_id' => 1,
            'name' => 'Bae',
            'slugified_name' => 'bae',
            'organization_no' => '556305-6059',
            'user_email' => 'nicklas.meurleflinta@baesystems.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura.hagglunds@baesystems.se',
            'invoice_reference' => 'Johan Nordin',
            'invoice_annotation' => '2400366740'
        ],
        [
            'id' => 24,
            'reseller_id' => 1,
            'name' => 'Hushallningssallskapet',
            'slugified_name' => 'hushallningssallskapet',
            'organization_no' => '556439-1489',
            'user_email' => 'nicklas.bengtsson@hushallningssallskapet.se',
            'invoice_type' => 'mail',
            'invoice_address' => 'Hushållningssällskapet Jönköping, Datorgatan 5, 561 33 HUSKVARNA',
            'invoice_reference' => 'Nicklas Bengtsson',
            'invoice_annotation' => ''
        ],
        [
            'id' => 25,
            'reseller_id' => 1,
            'name' => 'Smartoptics',
            'slugified_name' => 'smartoptics',
            'organization_no' => '556669-9921',
            'user_email' => 'per.burman@smartoptics.com',
            'invoice_type' => 'email',
            'invoice_address' => 'accounting.se@smartoptics.com',
            'invoice_reference' => 'Per Burman',
            'invoice_annotation' => 'Training system'
        ],
        [
            'id' => 26,
            'reseller_id' => 1,
            'name' => 'INSU AB',
            'slugified_name' => 'insu-ab',
            'organization_no' => '556369-9817',
            'user_email' => 'crister.modin@consid.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura@insu.se',
            'invoice_reference' => 'Jens Back',
            'invoice_annotation' => ''
        ],
        [
            'id' => 27,
            'reseller_id' => 1,
            'name' => 'Skellefteå Kraft',
            'slugified_name' => 'skelleftea-kraft',
            'organization_no' => '556016-2561',
            'user_email' => 'allan.lindgren@skekraft.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura.skab@skekraft.se',
            'invoice_reference' => 'Allan Lindgren',
            'invoice_annotation' => ''
        ],
        [
            'id' => 28,
            'reseller_id' => 1,
            'name' => 'Riigikontroll',
            'slugified_name' => 'riigikontroll',
            'organization_no' => 'https://www.riigikontroll.ee/',
            'user_email' => 'Krislin.Kivi@riigikontroll.ee',
            'invoice_type' => 'email',
            'invoice_address' => 'riigikontroll@riigikontroll.ee',
            'invoice_reference' => 'Krislin Kivi',
            'invoice_annotation' => 'EUROSAI IT'
        ],
        [
            'id' => 29,
            'reseller_id' => 1,
            'name' => 'Löf regionernas ömsesidiga försäkringsbolag',
            'slugified_name' => 'lof-regionernas-omsesidiga-forsakringsbolag',
            'organization_no' => '516401-8557',
            'user_email' => 'Pelle.Gustafson@lof.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'Löf regionernas ömsesidiga försäkringsbolag, Box 17830, 118 94 STOCKHOLM',
            'invoice_reference' => 'Pelle Gustafson',
            'invoice_annotation' => '6210'
        ],
        [
            'id' => 30,
            'reseller_id' => 1,
            'name' => 'Ermitage Partners AB',
            'slugified_name' => 'ermitage-partners-ab',
            'organization_no' => '559327-2601',
            'user_email' => 'frans@ermitage-partners.com',
            'invoice_type' => 'email',
            'invoice_address' => '29839969@scan.netvisor.fi',
            'invoice_reference' => 'Frans Mäkelä',
            'invoice_annotation' => ''
        ],
        [
            'id' => 31,
            'reseller_id' => 1,
            'name' => 'Höganäs Metal Powder AB',
            'slugified_name' => 'hoganas-metal-powder-ab',
            'organization_no' => '559159-9120',
            'user_email' => 'fredrik.vinnerborg@hoganas.com',
            'invoice_type' => 'email',
            'invoice_address' => 'reskontraHAB@hoganas.com',
            'invoice_reference' => 'Fredrik Vinnerborg',
            'invoice_annotation' => ''
        ],
        [
            'id' => 32,
            'reseller_id' => 1,
            'name' => 'Westermo',
            'slugified_name' => 'westermo',
            'organization_no' => '556361-2604',
            'user_email' => 'ant.lane@westermo.com',
            'invoice_type' => 'email',
            'invoice_address' => 'invoice_wte@westermo.com',
            'invoice_reference' => 'Ant Lane',
            'invoice_annotation' => '506473'
        ],
        [
            'id' => 33,
            'reseller_id' => null,
            'name' => 'Tullverket',
            'slugified_name' => 'tullverket',
            'organization_no' => '202100-0969',
            'user_email' => 'sup.invoices@redpill-linpro.com',
            'invoice_type' => 'email',
            'invoice_address' => 'sup.invoices@redpill-linpro.com',
            'invoice_reference' => 'Tony Nicolaides',
            'invoice_annotation' => 'Tullverket Moodle LMS',
        ],
        [
            'id' => 34,
            'reseller_id' => null,
            'name' => 'Svenska Draghundsportförbundet',
            'slugified_name' => 'svenska-draghundsportforbundet',
            'organization_no' => '817602-6840',
            'user_email' => 'sdsf@draghundsport.se',
            'invoice_type' => 'email',
            'invoice_address' => 'sdsf@draghundsport.se',
            'invoice_reference' => 'Jaana Tengman',
            'invoice_annotation' => '',
        ],
        [
            'id' => 35,
            'reseller_id' => null,
            'name' => 'Autotech Teknikinformation AB',
            'slugified_name' => 'autotech-teknikinformation-ab',
            'organization_no' => '556409-5353',
            'user_email' => 'faktura@autotech.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura@autotech.se',
            'invoice_reference' => 'Stefan Ferm',
            'invoice_annotation' => '',
        ],
        [
            'id' => 36,
            'reseller_id' => null,
            'name' => 'SVERIGES METEOROLOGISKA OCH HYDROLOGISKA INSTITUT',
            'slugified_name' => 'sveriges-meteorologiska-och-hydrologiska-institut',
            'organization_no' => '202100-0696',
            'user_email' => 'jan.karlsson@smhi.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'ekonomi@smhi.se',
            'invoice_reference' => 'Mikael Holm',
            'invoice_annotation' => '2021/1962/2.3',
        ],
        [
            'id' => 37,
            'reseller_id' => null,
            'name' => 'Arisone Academy',
            'slugified_name' => 'arisone-academy',
            'organization_no' => 'arisoneacademy.com',
            'user_email' => 'nadmyr@arisone.com',
            'invoice_type' => 'email',
            'invoice_address' => 'nadmyr@arisone.com',
            'invoice_reference' => 'Anna Nadmyr',
            'invoice_annotation' => '',
        ],
        [
            'id' => 38,
            'reseller_id' => null,
            'name' => 'Mansjouren',
            'slugified_name' => 'mansjouren',
            'organization_no' => '802012-9022',
            'user_email' => 'karolina@mansjouren.se',
            'invoice_type' => 'email',
            'invoice_address' => 'faktura@mansjouren.se',
            'invoice_reference' => 'Karolina',
            'invoice_annotation' => 'E-learningsystem Fristad',
        ],
        [
            'id' => 39,
            'reseller_id' => null,
            'name' => 'Lovefall',
            'slugified_name' => 'lovefall',
            'organization_no' => '559453-0726',
            'user_email' => 'nicke@lovefall.se',
            'invoice_type' => 'email',
            'invoice_address' => 'nicke@lovefall.se',
            'invoice_reference' => 'Nicklas Lovefall',
            'invoice_annotation' => '',
        ],
        [
            'id' => 40,
            'reseller_id' => null,
            'name' => 'Sida',
            'slugified_name' => 'sida',
            'organization_no' => '202100-4789',
            'user_email' => 'michal.alm@sida.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'michal.alm@sida.se',
            'invoice_reference' => 'Michael Alm',
            'invoice_annotation' => 'ZZ910801',
        ],
        [
            'id' => 41,
            'reseller_id' => null,
            'name' => 'Hanken',
            'slugified_name' => 'hanken',
            'organization_no' => 'hanken.fi',
            'user_email' => 'kicka.lindroos@hanken.fi',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'kicka.lindroos@hanken.fi',
            'invoice_reference' => 'Kicka Lindros',
            'invoice_annotation' => '',
        ],
        [
            'id' => 42,
            'reseller_id' => null,
            'name' => 'Skolverket',
            'slugified_name' => 'skolverket',
            'organization_no' => '202100-4185',
            'user_email' => 'user@skolverket.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'user@skolverket.se',
            'invoice_reference' => '2.7.3-2023:2819',
            'invoice_annotation' => 'SKO0001555',
        ],
        [
            'id' => 43,
            'reseller_id' => null,
            'name' => 'Sundsvallkommun',
            'slugified_name' => 'sundsvallkommun',
            'organization_no' => '556726-4758',
            'user_email' => 'tina.svingstedt@sundsvall.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'Chas Visual Management AB, Fack 2277, FE 1090 751 75 Uppsala',
            'invoice_reference' => 'Nathalie Sahlström',
            'invoice_annotation' => 'UH-2023-358',
        ],
        [
            'id' => 44,
            'reseller_id' => null,
            'name' => 'Ekonomistyrningsverket',
            'slugified_name' => 'ekonomistyrningsverket',
            'organization_no' => '202100-5026',
            'user_email' => 'johan.amtell@esv.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'Chas Visual Management AB, Fack 2277, FE 1090, 751 75 Uppsala',
            'invoice_reference' => 'Madeleine Dahl',
            'invoice_annotation' => '9000589',
        ],
        [
            'id' => 45,
            'reseller_id' => null,
            'name' => 'Socialstyrelsen',
            'slugified_name' => 'socialstyrelsen',
            'organization_no' => '202100-0555',
            'user_email' => 'federico.gonzalez@socialstyrelsen.se',
            'invoice_type' => 'e-invoice',
            'invoice_address' => 'Socialstyrelsen 10630 Stockholm',
            'invoice_reference' => 'Anna Aldehag',
            'invoice_annotation' => '27981/2024',
        ],
        [
            'id' => 46,
            'reseller_id' => null,
            'name' => 'Beijer Electronics AB',
            'slugified_name' => 'beijer-electronics-ab',
            'organization_no' => '55670143-2801',
            'user_email' => 'Marie-Louise.Syrjalainen@beijerelectronics.com',
            'invoice_type' => 'email',
            'invoice_address' => 'e-invoice.sweden@beijerelectronics.com',
            'invoice_reference' => 'Marie-Louise Syrjäläinen',
            'invoice_annotation' => 'LMS',
        ],
        [
            'id' => 47,
            'reseller_id' => null,
            'name' => 'RaySearch Laboratories AB',
            'slugified_name' => 'raysearch_labs',
            'organization_no' => '55632261-5701',
            'user_email' => 'andrea.hoeg@raysearchlabs.com',
            'invoice_type' => 'email',
            'invoice_address' => 'invoices@raysearchlabs.com',
            'invoice_reference' => 'Andrea Høeg',
            'invoice_annotation' => 'E-learning system SERVICE',
        ],
        [
            'id' => 48,
            'reseller_id' => null,
            'name' => 'GBA Key2Compliance AB',
            'slugified_name' => 'gba-key2compliance-ab',
            'organization_no' => '5566038104',
            'user_email' => 'hello@sparkfore.com',
            'invoice_type' => 'email',
            'invoice_address' => 'hello@sparkfore.com',
            'invoice_reference' => 'hello@sparkfore.com',
            'invoice_annotation' => 'hello@sparkfore.com',
        ]
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('resellers')->updateOrInsert([
            'cost_per_user_discount' => 0,
            'product_discount' => 0
        ]);

        // Insert data
        foreach ($this->customers as  $customer) {
            $insert = [
                'id' => $customer['id'],
                'name' => $customer['name'],
                'slugified_name' => $customer['slugified_name'],
                'organization_no' => $customer['organization_no'],
                'invoice_type' => $customer['invoice_type'],
                'invoice_email' => $customer['invoice_address'],
                'invoice_reference' => $customer['invoice_reference'],
                'invoice_annotation' => $customer['invoice_annotation'],
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString()
            ];

            Customer::updateOrCreate(
                ['id' => $customer['id']],
                $insert
            );

            User::updateOrCreate(
                ['email' => $customer['user_email']],
                [
                    'f_name' => strtok($customer['user_email'], '|'),
                    'l_name' => '',
                    'email' => $customer['user_email'],
                    'password' => Hash::make('password'),
                    'role_id' => 2,
                    'lang_id' => 1,
                    'account_type_id' => 1,
                    'customer_id' => $customer['id'],
                    'trial' => false,
                ]
            );
        }

        DB::statement("SELECT SETVAL(pg_get_serial_sequence('customers', 'id'), (SELECT MAX(id) FROM customers));");
    }
}
