<?php

namespace database\seeders;

use App\Domain\Jobs\SetInstallationJob;
use App\Domain\Models\Hosting;
use App\Domain\Models\InstallationTargetType;
use Illuminate\Database\Seeder;

class InstallationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        return;
        
        $installations =
            [
                [
                    'pipeline_name' => 'sparkfore',
                    'customer_id' => '1',
                    'hosting_id' => '19',
                    'url' => 'demo.sparkfore.com',
                    'include_staging_package' => '1',
                    'development_url' => 'testing.sparkfore.com',
                    'staging_url' => 'enterprise.next.sparkfore.com',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '1/1/2099',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/12/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'baseline',
                    'customer_id' => '1',
                    'hosting_id' => '10',
                    'url' => 'moodle.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '1/1/2099',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/12/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '2',
                    'hosting_id' => '10',
                    'url' => 'akeri.dgm.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/31/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/4/2020',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '2',
                    'hosting_id' => '20',
                    'url' => 'elearning.dgm.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '10/14/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/1/2011',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'ulla',
                    'customer_id' => '3',
                    'hosting_id' => '2',
                    'url' => 'moodle.ullapharmsci.org',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '11/30/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/30/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '2',
                    'customer_id' => '4',
                    'hosting_id' => '2',
                    'url' => 'lms.mil.se',
                    'include_staging_package' => '1',
                    'development_url' => 'mil-sandbox.sparkfore.com',
                    'staging_url' => 'staging.lms.mil.se',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '5/27/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '4/24/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '5',
                    'hosting_id' => '19',
                    'url' => 'akeri.instante.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/31/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/4/2019',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '4',
                    'customer_id' => '6',
                    'hosting_id' => '10',
                    'url' => 'dpc-elearning-rcf-cngof.instante.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '9/7/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/7/2020',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '4',
                    'customer_id' => '6',
                    'hosting_id' => '10',
                    'url' => 'neoventaacademy.instante.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '9/7/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/7/2020',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '7',
                    'hosting_id' => '10',
                    'url' => 'lms.pozacademy.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '8/24/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '8/24/2020',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '8',
                    'hosting_id' => '20',
                    'url' => 'mylearning.hoganas.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '1/1/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/1/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '31',
                    'hosting_id' => '19',
                    'url' => 'hoganas.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/15/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '9',
                    'hosting_id' => '10',
                    'url' => 'skogstransporter.instante.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '10/1/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '10/1/2012',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '10',
                    'hosting_id' => '25',
                    'url' => 'rsa.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '6/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '6/15/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '11',
                    'hosting_id' => '25',
                    'url' => 'jost-learning.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '5/27/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '5/27/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '2',
                    'customer_id' => '12',
                    'hosting_id' => '24',
                    'url' => 'agrol.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '9/2/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/2/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '13',
                    'hosting_id' => '25',
                    'url' => 'epr-training-academy.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/31/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/4/2020',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '2',
                    'customer_id' => '14',
                    'hosting_id' => '24',
                    'url' => 'recipharm.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '9/9/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '9/9/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '15',
                    'hosting_id' => '10',
                    'url' => 'r1.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/9/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '12/9/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '16',
                    'hosting_id' => '21',
                    'url' => 'bothnia.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/15/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '12/15/2021',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '17',
                    'hosting_id' => '10',
                    'url' => 'olofsfors.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/24/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/24/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '18',
                    'hosting_id' => '11',
                    'url' => 'brokkacademy.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '10/21/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '10/21/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '19',
                    'hosting_id' => '11',
                    'url' => 'meetme.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/1/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/1/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '20',
                    'hosting_id' => '11',
                    'url' => 'academy.dgm.nl',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '6/21/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '6/21/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '21',
                    'hosting_id' => '11',
                    'url' => 'utbildarna.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '6/1/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '6/1/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'skellefteakommun',
                    'customer_id' => '22',
                    'hosting_id' => '22',
                    'url' => 'larande.skelleftea.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => 'skelleftea.preview.sparkfore.com',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '1/16/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/16/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'bae',
                    'customer_id' => '23',
                    'hosting_id' => '22',
                    'url' => 'learning.baesystems.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => 'staging.learning.baesystems.se',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/13/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '12/13/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'hushallningssallskapet',
                    'customer_id' => '24',
                    'hosting_id' => '19',
                    'url' => 'webbkurs.hushallningssallskapet.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'hushallningssallskapet.staging.sparkfore.com/',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '6/8/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '6/8/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'smartoptics',
                    'customer_id' => '25',
                    'hosting_id' => '22',
                    'url' => 'training.smartoptics.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '3/23/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '3/23/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '6',
                    'customer_id' => '26',
                    'hosting_id' => '22',
                    'url' => 'insu.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '4/24/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '4/24/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '27',
                    'hosting_id' => '22',
                    'url' => 'larande.skekraft.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/8/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/8/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '28',
                    'hosting_id' => '2',
                    'url' => 'training.eurosai-it.org',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/7/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/7/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '29',
                    'hosting_id' => '22',
                    'url' => 'lof.instante.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '1/2/2023',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '1/2/2022',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'pipeline_name' => 'westermo',
                    'customer_id' => '32',
                    'hosting_id' => '2',
                    'url' => 'academy.westermo.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => 'westermo.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '6/20/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '6/20/2023',
                    'updated_at' => '9/12/2023',
                ],
                [
                    'product_id' => '6',
                    'customer_id' => '30',
                    'hosting_id' => '22',
                    'url' => 'entreacto.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2/15/2023',
                    'updated_at' => '9/12/2023',
                ],

                [
                    'pipeline_name' => 'tullverket',
                    'customer_id' => '33',
                    'hosting_id' => '2',
                    'url' => 'tullverket.internal.sparkfore.com',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'tv-utv.sparkfore.com',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/27/2023',
                    'updated_at' => '11/27/2023',
                ],

                [
                    'product_id' => '1',
                    'customer_id' => '34',
                    'hosting_id' => '2',
                    'url' => 'draghund.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/27/2023',
                    'updated_at' => '11/27/2023',
                ],

                [
                    'product_id' => '1',
                    'customer_id' => '35',
                    'hosting_id' => '2',
                    'url' => 'autotech.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/27/2023',
                    'updated_at' => '11/27/2023',
                ],

                [
                    'product_id' => '1',
                    'customer_id' => '11',
                    'hosting_id' => '11',
                    'url' => 'one-learning.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2/15/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/27/2023',
                    'updated_at' => '11/27/2023',
                ],

                [
                    'product_id' => '2',
                    'customer_id' => '36',
                    'hosting_id' => '22',
                    'url' => 'smhi.internal.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '12/12/2024',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '11/1/2021',
                    'updated_at' => '11/27/2023',
                ],

                [
                    'product_id' => '1',
                    'customer_id' => '37',
                    'hosting_id' => '2',
                    'url' => 'training.arisoneacademy.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2024-02-15',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2023-11-27',
                    'updated_at' => '2023-11-27'
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '6',
                    'hosting_id' => '2',
                    'url' => 'neoventa.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2024-02-15',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2023-11-27',
                    'updated_at' => '2023-11-27'
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '37',
                    'hosting_id' => '2',
                    'url' => 'training.arisoneacademy.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2024-02-15',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2023-12-05',
                    'updated_at' => '2023-12-05',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '38',
                    'hosting_id' => '2',
                    'url' => 'mansjouren.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2024-12-05',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2023-12-05',
                    'updated_at' => '2023-12-05',
                ],
                [ // excel id = 56
                    'pipeline_name' => 'lovefall',
                    'customer_id' => '39',
                    'hosting_id' => '2',
                    'url' => 'lms.sportvalues.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'lovefall.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2025-01-16',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [
                    'product_id' => '1',
                    'customer_id' => '16',
                    'hosting_id' => '2',
                    'url' => 'hantverksgruppen.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2025-01-16',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 59
                    'pipeline_name' => 'socialstyrelsen',
                    'customer_id' => '45',
                    'hosting_id' => '2',
                    'url' => 'donationsguiden.socialstyrelsen.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => 'donationsguiden.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 60
                    'pipeline_name' => 'sida',
                    'customer_id' => '40',
                    'hosting_id' => '2',
                    'url' => 'itp.sida.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'sida-itp.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 61
                    'pipeline_name' => 'sparkfore',
                    'customer_id' => '1',
                    'hosting_id' => '2',
                    'url' => 'learning.samarbetsmiljo.se',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 62
                    'pipeline_name' => 'sida',
                    'customer_id' => '40',
                    'hosting_id' => '2',
                    'url' => 'learning.sida.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'sida-learning.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 63
                    'pipeline_name' => 'sparkfore',
                    'customer_id' => '29',
                    'hosting_id' => '2',
                    'url' => 'lof.sparkfore.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 64
                    'pipeline_name' => 'sida',
                    'customer_id' => '40',
                    'hosting_id' => '2',
                    'url' => 'partnership.sida.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'sida-partnership.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                 [// excel id = 65
                    'pipeline_name' => 'skolverket',
                    'customer_id' => '42',
                    'hosting_id' => '2',
                    'url' => 'skolchefsutbildningen.skolverket.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'skolverket.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 66
                    'pipeline_name' => 'sparkfore',
                    'customer_id' => '6',
                    'hosting_id' => '2',
                    'url' => 'surveillancefoetale.cngof.fr',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-01-16',
                    'updated_at' => '2024-01-17',
                ],
                [// excel id = 67
                    'pipeline_name' => 'hanken',
                    'customer_id' => '41',
                    'hosting_id' => '21',
                    'url' => 'hanken.internal.sparkfore.com',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'hanken.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-09-02',
                    'updated_at' => '2024-09-02',
                ],
                [// excel id = 68
                    'product_id' => '32',
                    'customer_id' => '44',
                    'hosting_id' => '2',
                    'url' => 'utbildning.esv.se',
                    'include_staging_package' => '1',
                    'development_url' => '',
                    'staging_url' => 'esv.staging.sparkfore.com',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2024-09-02',
                    'updated_at' => '2024-09-02',
                ],
                [// excel id = 70
                    'product_id' => '1',
                    'customer_id' => '48',
                    'hosting_id' => '2',
                    'url' => 'lms.key2compliance.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '1',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2025-03-18',
                    'updated_at' => '2025-03-18',
                ],
                [// excel id = 71
                    'product_id' => '1',
                    'customer_id' => '46',
                    'hosting_id' => '2',
                    'url' => 'academy.beijerelectronics.com',
                    'include_staging_package' => '0',
                    'development_url' => '',
                    'staging_url' => '',
                    'include_backup' => '0',
                    'general_terms_agreement' => '1',
                    'billing_terms_agreement' => '1',
                    'date_contract_ends' => '2099-01-01',
                    'date_contract_terminate' => '0',
                    'status_enum' => '1',
                    'created_at' => '2025-03-18',
                    'updated_at' => '2025-03-18',
                ]

            ];

            $installationTargetTypes = InstallationTargetType::whereIn('key', ['production', 'staging', 'development'])->get();

            foreach ($installations as $k => $installationArray) {
                $installation = (object) $installationArray;

                $hosting = Hosting::find($installation->hosting_id);

                $statusTypeKey = '';
                if ($hosting->hostingProvider->key == HOSTING_ON_PREM) {
                    $statusTypeKey = 'on-premise';
                } elseif ($installation->status_enum == 1) {
                    $statusTypeKey = 'online';
                } else {
                    $statusTypeKey = 'offline';
                }

                $element = [
                    'hosting_id' => $installation->hosting_id,
                    'include_staging_package' => $installation->include_staging_package,
                    'include_backup' => $installation->include_backup,
                    'general_terms_agreement' => $installation->general_terms_agreement,
                    'billing_terms_agreement' => $installation->billing_terms_agreement,
                    'date_contract_ends' => $installation->date_contract_ends,
                    'date_contract_terminate' => $installation->date_contract_terminate,
                    'status' => $statusTypeKey,
                    'created_at' => $installation->created_at,
                    'updated_at' => $installation->updated_at
                ];

                $urls = [
                    'production' => $installation->url,
                    'staging' => $installation->staging_url,
                    'development' => $installation->development_url
                ];

                foreach ($urls as $type => $url) {
                    if (!empty($url)) {
                        $element["url"] = $url;
                        $element["domain_type"] = $this->getDomainType($url);
                        $element["installation_target_type_id"] = $installationTargetTypes->where("key", $type)->first()->id;
                        dispatch(new SetInstallationJob($installationArray, $element))->onQueue('pluginsSync');
                    }
                }
            }
        }

        private function getDomainType($url) {
            if (strpos($url, 'sparkfore.com') !== false) {
                return'standard';
            } else {
                return 'custom';
            }
        }
    }
